=== ayman-aks/ayman-aks.github.io/akansous.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="website">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="language" type="xs:string"/>
                <xs:element name="navbar">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="text" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="id" type="xs:integer" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="general">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="home">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="text" type="xs:string"/>
                            <xs:element name="pronoun" type="xs:string"/>
                            <xs:element name="job" type="xs:string"/>
                            <xs:element name="city" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="about">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="text" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="id" type="xs:integer" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="birth" type="xs:string"/>
                            <xs:element name="address" type="xs:string"/>
                            <xs:element name="zip" type="xs:string"/>
                            <xs:element name="email" type="xs:string"/>
                            <xs:element name="phone" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Resume">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="text" type="xs:string"/>
                            <xs:element name="download" type="xs:string"/>
                            <xs:element name="link" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Skills">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="skill" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="detail" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="contact">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="address">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="text" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="number">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="text" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="mail">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="text" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="linkedin">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="title" type="xs:string"/>
                                        <xs:element name="text" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="email" type="xs:string"/>
                            <xs:element name="subject" type="xs:string"/>
                            <xs:element name="message" type="xs:string"/>
                            <xs:element name="button" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="video" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ayman-aks/ayman-aks.github.io/contentfr.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="transform.xsl"?>
<website xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="akansous.xsd">
    <language>fr</language>
    <navbar>
        <text id="1">Accueil</text>
        <text id="2">À propos</text>
        <text id="3">CV</text>
        <text id="4">Compétences en Sémantique Web</text>
        <text id="5">Contact</text>
    </navbar>

    <general>
        <name>Ayman AKANSOUS</name>
    </general>

    <home>
        <text>Bonjour!</text>
        <pronoun>Je suis</pronoun>
        <job>Un Ingénieur Logiciel</job>
        <city>Basé à Paris</city>
    </home>

    <about>
        <title>À propos de moi</title>
        <text id="1">Nom</text>
        <text id="2">Date de naissance</text>
        <text id="3">Adresse</text>
        <text id="4">Code postal</text>
        <text id="5">Email</text>
        <text id="6">Téléphone</text>
        <birth>18 juin 2001</birth>
        <address>Montmagny</address>
        <zip>95360</zip>
        <email>aymanakansous@outlook.com</email>
        <phone>+33749693627</phone>
    </about>

    <Resume>
        <title>CV</title>
        <text>Passionné par l'informatique depuis toujours, j'ai choisi le domaine de l'ingénierie informatique. C'est le domaine où je peux satisfaire ma passion et être à jour avec l'augmentation de la numérisation dans le monde.</text>
        <download>Voir CV</download>
        <link>cvfr.xml</link>
    </Resume>

    <Skills>
        <title>Mes Compétences</title>
        <skill>
            <title>RDF</title>
            <detail>
            RDF (Resource Description Framework) est un modèle standard pour l'échange de données sur le web. RDF permet la fusion de données même si les schémas sous-jacents diffèrent, et il prend en charge l'évolution des schémas au fil du temps sans nécessiter la modification de tous les consommateurs de données.
            </detail>
        </skill>

        <skill>
            <title>RDFs</title>
            <detail>
            RDF Schema (RDFS) fournit un vocabulaire de modélisation de données pour les données RDF. Il étend RDF en fournissant des mécanismes pour décrire des groupes de ressources connexes et les relations entre ces ressources. RDFS permet la création d'une taxonomie de classes et de propriétés, facilitant des descriptions de données plus riches.
            </detail>
        </skill>

        <skill>
            <title>RDFa</title>
            <detail>
            RDFa (Resource Description Framework in Attributes) est une spécification pour les attributs à utiliser avec HTML, XHTML et d'autres types de documents basés sur XML pour exprimer des données structurées. RDFa permet d'intégrer des métadonnées RDF dans les documents web, rendant les données facilement accessibles aux machines pour le traitement.
            </detail>
        </skill>

        <skill>
            <title>XSL</title>
            <detail>
            XSL (Extensible Stylesheet Language) est un langage pour exprimer des feuilles de style. Il est principalement utilisé pour transformer des documents XML en d'autres formats tels que HTML, texte brut ou autres schémas XML. XSLT, une partie de XSL, permet la transformation de données XML en différents formats, offrant ainsi une flexibilité dans la présentation et le partage des données XML.
            </detail>
        </skill>
    </Skills>

    <contact>
        <address>
          <title>ADRESSE</title>
          <text>95360, Montmagny </text>
        </address>
        <number>
          <title>NUMÉRO DE CONTACT</title>
          <text>+33749693627</text>
        </number>
        <mail>
          <title>ADRESSE EMAIL</title>
          <text>aymanakansous@outlook.com</text>
        </mail>
        <linkedin>
          <title>LinkedIn</title>
          <text>https://www.linkedin.com/in/ayman-akansous-686b5a134/</text>
        </linkedin>
        <name>Votre Nom</name>
        <email>Email</email>
        <subject>Sujet</subject>
        <message>Message</message>
        <button>ENVOYER MESSAGE</button>
    </contact>
    <video>https://www.youtube.com/embed/Xep0zcHzclo?si=sWOzVSHMupdboiJu</video>
</website>

=== ayman-aks/ayman-aks.github.io/contenten.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="transform.xsl"?>
<website xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="akansous.xsd">
    <language>en</language>
    <navbar>
        <text id="1">Home</text>
        <text id="2">About</text>
        <text id="3">Resume</text>
        <text id="4">Skills In Web Semantic</text>
        <text id="5">Contact</text>
    </navbar>

    <general>
        <name>Ayman AKANSOUS</name>
    </general>

    <home>
        <text>Hello!</text>
        <pronoun>I'm</pronoun>
        <job>A Software Engineer</job>
        <city>Based in Paris</city>
    </home>

    <about>
        <title>About me</title>
        <text id="1">Name</text>
        <text id="2">Date of birth</text>
        <text id="3">Address</text>
        <text id="4">Zip code</text>
        <text id="5">Email</text>
        <text id="6">Phone</text>
        <birth>June 18,2001</birth>
        <address>Montmagny</address>
        <zip>95360</zip>
        <email>aymanakansous@outlook.com</email>
        <phone>+33749693627</phone>
    </about>

    <Resume>
        <title>Resume</title>
        <text>Passionate about computer science since always, I chose as a field of computer engineering, this is the field where I can satisfy my passion and be up to date with the increase of digitization in the world.</text>
        <download>Show CV</download>
        <link>cven.xml</link>
    </Resume>

    <Skills>
        <title>My Skills</title>
        <skill>
            <title>RDF</title>
            <detail>
            RDF (Resource Description Framework) is a standard model for data interchange on the web. RDF allows the merging of data even if the underlying schemas differ, and it specifically supports the evolution of schemas over time without requiring all the data consumers to be changed.
            </detail>
        </skill>

        <skill>
            <title>RDFs</title>
            <detail>
            RDF Schema (RDFS) provides a data-modelling vocabulary for RDF data. It extends RDF by providing mechanisms for describing groups of related resources and the relationships between these resources. RDFS allows for the creation of a taxonomy of classes and properties, facilitating richer data descriptions.
            </detail>
        </skill>

        <skill>
            <title>RDFa</title>
            <detail>
            RDFa (Resource Description Framework in Attributes) is a specification for attributes to be used with HTML, XHTML, and other XML-based document types to express structured data. RDFa enables embedding RDF metadata within web documents, making the data easily accessible to machines for processing.
            </detail>
        </skill>

        <skill>
            <title>XSL</title>
            <detail>
            XSL (Extensible Stylesheet Language) is a language for expressing stylesheets. It is primarily used to transform XML documents into other formats such as HTML, plain text, or other XML schemas. XSLT, a part of XSL, allows for the transformation of XML data into different formats, providing flexibility in presenting and sharing XML data.
            </detail>
        </skill>
    </Skills>

    <contact>
        <address>
          <title>ADDRESS</title>
          <text>95360, Montmagny </text>
        </address>
        <number>
          <title>CONTACT NUMBER</title>
          <text>+33749693627</text>
        </number>
        <mail>
          <title>EMAIL ADDRESS</title>
          <text>aymanakansous@outlook.com</text>
        </mail>
        <linkedin>
          <title>Linkedin</title>
          <text>https://www.linkedin.com/in/ayman-akansous-686b5a134/</text>
        </linkedin>
        <name>Your Name</name>
        <email>Email</email>
        <subject>Subject</subject>
        <message>Message</message>
        <button>SEND MESSAGE</button>
    </contact>
    <video>https://www.youtube.com/embed/kjPqZQ0ZHpg?si=UIzpFywAlvrGpfav</video>
</website>
